// 500 records generated to display scalability.
export var data = [
    { mmr: 2242, username: "secured line" },
    { mmr: 3391, username: "logistical" },
    { mmr: 2541, username: "archive" },
    { mmr: 3083, username: "Extended" },
    { mmr: 3772, username: "moratorium" },
    { mmr: 3486, username: "Public-key" },
    { mmr: 3867, username: "User-friendly" },
    { mmr: 3255, username: "system-worthy" },
    { mmr: 3178, username: "scalable" },
    { mmr: 3877, username: "context-sensitive" },
    { mmr: 2751, username: "maximized" },
    { mmr: 2984, username: "value-added" },
    { mmr: 3041, username: "clear-thinking" },
    { mmr: 3335, username: "attitude-oriented" },
    { mmr: 3713, username: "Exclusive" },
    { mmr: 3200, username: "Enhanced" },
    { mmr: 3962, username: "Public-key" },
    { mmr: 3334, username: "Multi-channelled" },
    { mmr: 2493, username: "functionalities" },
    { mmr: 2903, username: "Front-line" },
    { mmr: 2088, username: "Down-sized" },
    { mmr: 3148, username: "time-frame" },
    { mmr: 3050, username: "content-based" },
    { mmr: 2089, username: "6th generation" },
    { mmr: 2496, username: "Customizable" },
    { mmr: 2315, username: "Monitored" },
    { mmr: 3803, username: "disintermediate" },
    { mmr: 2336, username: "Implemented" },
    { mmr: 3063, username: "secured line" },
    { mmr: 2878, username: "projection" },
    { mmr: 3885, username: "Networked" },
    { mmr: 2198, username: "product" },
    { mmr: 2187, username: "Diverse" },
    { mmr: 3119, username: "customer loyalty" },
    { mmr: 2551, username: "Grass-roots" },
    { mmr: 3446, username: "secondary" },
    { mmr: 2177, username: "info-mediaries" },
    { mmr: 2122, username: "global" },
    { mmr: 2466, username: "access" },
    { mmr: 3983, username: "software" },
    { mmr: 2065, username: "Streamlined" },
    { mmr: 3128, username: "3rd generation" },
    { mmr: 2212, username: "modular" },
    { mmr: 2698, username: "Proactive" },
    { mmr: 2578, username: "Enhanced" },
    { mmr: 2833, username: "Public-key" },
    { mmr: 3236, username: "support" },
    { mmr: 3744, username: "eco-centric" },
    { mmr: 3481, username: "national" },
    { mmr: 3191, username: "scalable" },
    { mmr: 2549, username: "radical" },
    { mmr: 2505, username: "core" },
    { mmr: 2026, username: "support" },
    { mmr: 2401, username: "local area network" },
    { mmr: 2725, username: "Stand-alone" },
    { mmr: 2576, username: "Fully-configurable" },
    { mmr: 2049, username: "fresh-thinking" },
    { mmr: 3807, username: "Object-based" },
    { mmr: 2816, username: "challenge" },
    { mmr: 3026, username: "motivating" },
    { mmr: 2758, username: "interface" },
    { mmr: 3389, username: "asymmetric" },
    { mmr: 2692, username: "application" },
    { mmr: 2634, username: "next generation" },
    { mmr: 3068, username: "Multi-layered" },
    { mmr: 2422, username: "bottom-line" },
    { mmr: 3443, username: "client-driven" },
    { mmr: 2592, username: "Monitored" },
    { mmr: 3400, username: "monitoring" },
    { mmr: 3745, username: "workforce" },
    { mmr: 2643, username: "cohesive" },
    { mmr: 3558, username: "Devolved" },
    { mmr: 3994, username: "Cloned" },
    { mmr: 3319, username: "hybrid" },
    { mmr: 3251, username: "maximized" },
    { mmr: 3299, username: "systematic" },
    { mmr: 2453, username: "Horizontal" },
    { mmr: 3651, username: "grid-enabled" },
    { mmr: 2948, username: "interface" },
    { mmr: 3470, username: "groupware" },
    { mmr: 2282, username: "moratorium" },
    { mmr: 3236, username: "demand-driven" },
    { mmr: 3264, username: "secured line" },
    { mmr: 2286, username: "dynamic" },
    { mmr: 3819, username: "alliance" },
    { mmr: 2266, username: "homogeneous" },
    { mmr: 2156, username: "zero administration" },
    { mmr: 3628, username: "portal" },
    { mmr: 3275, username: "real-time" },
    { mmr: 3384, username: "focus group" },
    { mmr: 3612, username: "background" },
    { mmr: 3158, username: "heuristic" },
    { mmr: 2279, username: "Integrated" },
    { mmr: 2516, username: "paradigm" },
    { mmr: 2126, username: "empowering" },
    { mmr: 3245, username: "optimizing" },
    { mmr: 3037, username: "Function-based" },
    { mmr: 3399, username: "Front-line" },
    { mmr: 3454, username: "Self-enabling" },
    { mmr: 2624, username: "Function-based" },
    { mmr: 2370, username: "web-enabled" },
    { mmr: 3118, username: "Stand-alone" },
    { mmr: 3360, username: "homogeneous" },
    { mmr: 2675, username: "Optional" },
    { mmr: 2865, username: "Object-based" },
    { mmr: 3436, username: "didactic" },
    { mmr: 2492, username: "open architecture" },
    { mmr: 3184, username: "Virtual" },
    { mmr: 2846, username: "focus group" },
    { mmr: 2153, username: "Reverse-engineered" },
    { mmr: 3936, username: "Fundamental" },
    { mmr: 3720, username: "info-mediaries" },
    { mmr: 3164, username: "Profound" },
    { mmr: 2496, username: "Face to face" },
    { mmr: 3708, username: "help-desk" },
    { mmr: 2497, username: "Secured" },
    { mmr: 3738, username: "contextually-based" },
    { mmr: 2936, username: "Switchable" },
    { mmr: 2199, username: "transitional" },
    { mmr: 3465, username: "next generation" },
    { mmr: 2228, username: "task-force" },
    { mmr: 3160, username: "bandwidth-monitored" },
    { mmr: 2934, username: "dynamic" },
    { mmr: 2078, username: "Expanded" },
    { mmr: 3184, username: "circuit" },
    { mmr: 2985, username: "systemic" },
    { mmr: 2939, username: "encoding" },
    { mmr: 2489, username: "Organized" },
    { mmr: 2204, username: "empowering" },
    { mmr: 3360, username: "zero tolerance" },
    { mmr: 2188, username: "zero defect" },
    { mmr: 3549, username: "empowering" },
    { mmr: 2912, username: "tertiary" },
    { mmr: 3694, username: "Multi-layered" },
    { mmr: 3133, username: "mobile" },
    { mmr: 3099, username: "Optimized" },
    { mmr: 2583, username: "array" },
    { mmr: 3874, username: "Sharable" },
    { mmr: 3464, username: "hierarchy" },
    { mmr: 2543, username: "next generation" },
    { mmr: 2781, username: "3rd generation" },
    { mmr: 3486, username: "global" },
    { mmr: 2957, username: "neutral" },
    { mmr: 2813, username: "leverage" },
    { mmr: 3067, username: "dynamic" },
    { mmr: 3719, username: "workforce" },
    { mmr: 2843, username: "systematic" },
    { mmr: 3644, username: "Networked" },
    { mmr: 2485, username: "Cross-group" },
    { mmr: 2408, username: "leverage" },
    { mmr: 2979, username: "Seamless" },
    { mmr: 3516, username: "neural-net" },
    { mmr: 3855, username: "leverage" },
    { mmr: 3676, username: "projection" },
    { mmr: 2974, username: "dedicated" },
    { mmr: 3339, username: "value-added" },
    { mmr: 3004, username: "frame" },
    { mmr: 2550, username: "even-keeled" },
    { mmr: 3215, username: "client-server" },
    { mmr: 2449, username: "Adaptive" },
    { mmr: 3181, username: "local" },
    { mmr: 2831, username: "encompassing" },
    { mmr: 3135, username: "success" },
    { mmr: 2433, username: "Focused" },
    { mmr: 2874, username: "data-warehouse" },
    { mmr: 3634, username: "background" },
    { mmr: 2996, username: "heuristic" },
    { mmr: 3221, username: "zero tolerance" },
    { mmr: 2062, username: "Digitized" },
    { mmr: 2254, username: "open architecture" },
    { mmr: 3794, username: "hardware" },
    { mmr: 3025, username: "Expanded" },
    { mmr: 3657, username: "clear-thinking" },
    { mmr: 2501, username: "Versatile" },
    { mmr: 3701, username: "infrastructure" },
    { mmr: 3434, username: "background" },
    { mmr: 3170, username: "hub" },
    { mmr: 2304, username: "Profound" },
    { mmr: 3810, username: "attitude" },
    { mmr: 2324, username: "Implemented" },
    { mmr: 3673, username: "Front-line" },
    { mmr: 3468, username: "even-keeled" },
    { mmr: 3389, username: "framework" },
    { mmr: 3677, username: "asynchronous" },
    { mmr: 2020, username: "Versatile" },
    { mmr: 3889, username: "asymmetric" },
    { mmr: 3726, username: "local area network" },
    { mmr: 3590, username: "dynamic" },
    { mmr: 3607, username: "needs-based" },
    { mmr: 3015, username: "paradigm" },
    { mmr: 2125, username: "frame" },
    { mmr: 3188, username: "Organic" },
    { mmr: 2864, username: "website" },
    { mmr: 3698, username: "context-sensitive" },
    { mmr: 2755, username: "migration" },
    { mmr: 2579, username: "Persevering" },
    { mmr: 2490, username: "Business-focused" },
    { mmr: 3078, username: "Extended" },
    { mmr: 2461, username: "web-enabled" },
    { mmr: 2570, username: "secured line" },
    { mmr: 2857, username: "Customizable" },
    { mmr: 3710, username: "Triple-buffered" },
    { mmr: 2452, username: "Optimized" },
    { mmr: 3622, username: "model" },
    { mmr: 2621, username: "reciprocal" },
    { mmr: 3775, username: "Cross-platform" },
    { mmr: 2455, username: "24 hour" },
    { mmr: 2819, username: "Re-engineered" },
    { mmr: 2281, username: "coherent" },
    { mmr: 3876, username: "analyzing" },
    { mmr: 3365, username: "optimizing" },
    { mmr: 2057, username: "dedicated" },
    { mmr: 3031, username: "Optional" },
    { mmr: 3409, username: "Robust" },
    { mmr: 3900, username: "Cross-platform" },
    { mmr: 3453, username: "Total" },
    { mmr: 2698, username: "Seamless" },
    { mmr: 3863, username: "tangible" },
    { mmr: 3608, username: "parallelism" },
    { mmr: 2365, username: "Ameliorated" },
    { mmr: 2494, username: "Total" },
    { mmr: 3692, username: "Multi-tiered" },
    { mmr: 3103, username: "Synchronised" },
    { mmr: 2377, username: "Extended" },
    { mmr: 2564, username: "Quality-focused" },
    { mmr: 2069, username: "grid-enabled" },
    { mmr: 2902, username: "leading edge" },
    { mmr: 2670, username: "Exclusive" },
    { mmr: 2396, username: "Polarised" },
    { mmr: 2675, username: "Managed" },
    { mmr: 3304, username: "Adaptive" },
    { mmr: 3028, username: "6th generation" },
    { mmr: 3975, username: "Sharable" },
    { mmr: 2724, username: "composite" },
    { mmr: 2299, username: "Down-sized" },
    { mmr: 2471, username: "portal" },
    { mmr: 3592, username: "Fundamental" },
    { mmr: 3108, username: "project" },
    { mmr: 3068, username: "background" },
    { mmr: 2527, username: "Team-oriented" },
    { mmr: 2864, username: "leading edge" },
    { mmr: 2343, username: "uniform" },
    { mmr: 2353, username: "approach" },
    { mmr: 2472, username: "time-frame" },
    { mmr: 3172, username: "user-facing" },
    { mmr: 3513, username: "Sharable" },
    { mmr: 3881, username: "Customer-focused" },
    { mmr: 2875, username: "local" },
    { mmr: 2663, username: "superstructure" },
    { mmr: 2396, username: "superstructure" },
    { mmr: 3199, username: "mobile" },
    { mmr: 2611, username: "Multi-layered" },
    { mmr: 2411, username: "national" },
    { mmr: 2282, username: "4th generation" },
    { mmr: 3256, username: "Secured" },
    { mmr: 2183, username: "Front-line" },
    { mmr: 3427, username: "collaboration" },
    { mmr: 3119, username: "modular" },
    { mmr: 3995, username: "Extended" },
    { mmr: 3539, username: "human-resource" },
    { mmr: 3763, username: "Multi-layered" },
    { mmr: 3570, username: "Pre-emptive" },
    { mmr: 2041, username: "secured line" },
    { mmr: 2981, username: "throughput" },
    { mmr: 3328, username: "User-friendly" },
    { mmr: 2178, username: "contextually-based" },
    { mmr: 2049, username: "Sharable" },
    { mmr: 2342, username: "functionalities" },
    { mmr: 2785, username: "multi-tasking" },
    { mmr: 2389, username: "Profit-focused" },
    { mmr: 2203, username: "orchestration" },
    { mmr: 2293, username: "Operative" },
    { mmr: 3696, username: "Graphic Interface" },
    { mmr: 3065, username: "24/7" },
    { mmr: 3373, username: "Sharable" },
    { mmr: 3680, username: "migration" },
    { mmr: 3097, username: "bottom-line" },
    { mmr: 2226, username: "Open-source" },
    { mmr: 3814, username: "Centralized" },
    { mmr: 3579, username: "maximized" },
    { mmr: 2073, username: "interface" },
    { mmr: 2265, username: "secured line" },
    { mmr: 3309, username: "object-oriented" },
    { mmr: 3760, username: "strategy" },
    { mmr: 3141, username: "Decentralized" },
    { mmr: 3545, username: "tertiary" },
    { mmr: 3935, username: "capacity" },
    { mmr: 3101, username: "Vision-oriented" },
    { mmr: 3270, username: "infrastructure" },
    { mmr: 2410, username: "Fundamental" },
    { mmr: 3384, username: "Monitored" },
    { mmr: 2467, username: "architecture" },
    { mmr: 3083, username: "hierarchy" },
    { mmr: 2801, username: "methodology" },
    { mmr: 3658, username: "solution" },
    { mmr: 3251, username: "collaboration" },
    { mmr: 2433, username: "pricing structure" },
    { mmr: 3655, username: "Secured" },
    { mmr: 3774, username: "leverage" },
    { mmr: 3540, username: "open architecture" },
    { mmr: 3833, username: "User-centric" },
    { mmr: 2875, username: "bottom-line" },
    { mmr: 3133, username: "algorithm" },
    { mmr: 3468, username: "Managed" },
    { mmr: 3111, username: "24/7" },
    { mmr: 3670, username: "superstructure" },
    { mmr: 3255, username: "mission-critical" },
    { mmr: 2974, username: "client-driven" },
    { mmr: 2379, username: "Graphical User Interface" },
    { mmr: 2776, username: "internet solution" },
    { mmr: 2062, username: "6th generation" },
    { mmr: 3608, username: "synergy" },
    { mmr: 3680, username: "Business-focused" },
    { mmr: 2562, username: "Realigned" },
    { mmr: 3118, username: "Compatible" },
    { mmr: 3987, username: "leading edge" },
    { mmr: 2328, username: "policy" },
    { mmr: 3613, username: "6th generation" },
    { mmr: 3480, username: "radical" },
    { mmr: 2232, username: "leading edge" },
    { mmr: 3096, username: "systematic" },
    { mmr: 2491, username: "hierarchy" },
    { mmr: 2063, username: "customer loyalty" },
    { mmr: 3722, username: "responsive" },
    { mmr: 2199, username: "leverage" },
    { mmr: 2087, username: "national" },
    { mmr: 3464, username: "Public-key" },
    { mmr: 2220, username: "client-server" },
    { mmr: 3055, username: "4th generation" },
    { mmr: 2606, username: "context-sensitive" },
    { mmr: 3192, username: "strategy" },
    { mmr: 3028, username: "Synchronised" },
    { mmr: 3172, username: "attitude-oriented" },
    { mmr: 3915, username: "well-modulated" },
    { mmr: 2652, username: "disintermediate" },
    { mmr: 3567, username: "Implemented" },
    { mmr: 2764, username: "monitoring" },
    { mmr: 2135, username: "groupware" },
    { mmr: 3452, username: "Business-focused" },
    { mmr: 2183, username: "structure" },
    { mmr: 2720, username: "client-server" },
    { mmr: 3205, username: "impactful" },
    { mmr: 2669, username: "Configurable" },
    { mmr: 3103, username: "monitoring" },
    { mmr: 2564, username: "local" },
    { mmr: 2832, username: "Streamlined" },
    { mmr: 2731, username: "multi-state" },
    { mmr: 3224, username: "homogeneous" },
    { mmr: 2856, username: "fresh-thinking" },
    { mmr: 2175, username: "success" },
    { mmr: 2721, username: "ability" },
    { mmr: 3543, username: "monitoring" },
    { mmr: 3067, username: "Synergistic" },
    { mmr: 3642, username: "upward-trending" },
    { mmr: 2269, username: "local" },
    { mmr: 3166, username: "Sharable" },
    { mmr: 2804, username: "Multi-tiered" },
    { mmr: 2888, username: "orchestration" },
    { mmr: 2551, username: "5th generation" },
    { mmr: 3347, username: "superstructure" },
    { mmr: 3295, username: "Multi-lateral" },
    { mmr: 2152, username: "infrastructure" },
    { mmr: 2663, username: "product" },
    { mmr: 3730, username: "Intuitive" },
    { mmr: 2933, username: "policy" },
    { mmr: 3405, username: "Configurable" },
    { mmr: 2182, username: "content-based" },
    { mmr: 3486, username: "context-sensitive" },
    { mmr: 2675, username: "Secured" },
    { mmr: 2762, username: "project" },
    { mmr: 3293, username: "synergy" },
    { mmr: 3079, username: "architecture" },
    { mmr: 2412, username: "matrix" },
    { mmr: 3354, username: "global" },
    { mmr: 2407, username: "Right-sized" },
    { mmr: 2378, username: "Graphic Interface" },
    { mmr: 2175, username: "Organic" },
    { mmr: 2290, username: "Optimized" },
    { mmr: 3291, username: "time-frame" },
    { mmr: 2382, username: "forecast" },
    { mmr: 2086, username: "neutral" },
    { mmr: 2979, username: "De-engineered" },
    { mmr: 2442, username: "executive" },
    { mmr: 3928, username: "non-volatile" },
    { mmr: 3762, username: "Reduced" },
    { mmr: 3832, username: "interface" },
    { mmr: 3069, username: "Synergized" },
    { mmr: 3564, username: "encompassing" },
    { mmr: 3817, username: "Synergistic" },
    { mmr: 2231, username: "national" },
    { mmr: 3520, username: "extranet" },
    { mmr: 3021, username: "secondary" },
    { mmr: 3879, username: "analyzing" },
    { mmr: 3068, username: "portal" },
    { mmr: 3261, username: "value-added" },
    { mmr: 3671, username: "architecture" },
    { mmr: 2361, username: "Up-sized" },
    { mmr: 2979, username: "Proactive" },
    { mmr: 3022, username: "next generation" },
    { mmr: 2200, username: "Persevering" },
    { mmr: 2416, username: "secured line" },
    { mmr: 3273, username: "matrices" },
    { mmr: 2354, username: "motivating" },
    { mmr: 2558, username: "Future-proofed" },
    { mmr: 3604, username: "impactful" },
    { mmr: 3579, username: "frame" },
    { mmr: 2544, username: "Focused" },
    { mmr: 2022, username: "Operative" },
    { mmr: 2679, username: "even-keeled" },
    { mmr: 2798, username: "Multi-channelled" },
    { mmr: 3279, username: "Multi-lateral" },
    { mmr: 3332, username: "web-enabled" },
    { mmr: 3337, username: "model" },
    { mmr: 3659, username: "installation" },
    { mmr: 2694, username: "content-based" },
    { mmr: 2963, username: "motivating" },
    { mmr: 3806, username: "homogeneous" },
    { mmr: 2248, username: "moratorium" },
    { mmr: 3794, username: "tangible" },
    { mmr: 3254, username: "application" },
    { mmr: 2486, username: "intermediate" },
    { mmr: 2315, username: "access" },
    { mmr: 3456, username: "intangible" },
    { mmr: 3802, username: "didactic" },
    { mmr: 2274, username: "Multi-lateral" },
    { mmr: 2053, username: "user-facing" },
    { mmr: 3954, username: "initiative" },
    { mmr: 3308, username: "encoding" },
    { mmr: 2600, username: "throughput" },
    { mmr: 3756, username: "hybrid" },
    { mmr: 3103, username: "infrastructure" },
    { mmr: 3917, username: "Triple-buffered" },
    { mmr: 2219, username: "Quality-focused" },
    { mmr: 2780, username: "Progressive" },
    { mmr: 2504, username: "even-keeled" },
    { mmr: 2930, username: "User-centric" },
    { mmr: 2560, username: "utilisation" },
    { mmr: 3897, username: "responsive" },
    { mmr: 2672, username: "function" },
    { mmr: 2503, username: "4th generation" },
    { mmr: 2848, username: "24 hour" },
    { mmr: 2130, username: "productivity" },
    { mmr: 3599, username: "motivating" },
    { mmr: 3877, username: "transitional" },
    { mmr: 3727, username: "Assimilated" },
    { mmr: 2748, username: "encoding" },
    { mmr: 3880, username: "3rd generation" },
    { mmr: 2917, username: "internet solution" },
    { mmr: 2898, username: "model" },
    { mmr: 2095, username: "hardware" },
    { mmr: 2180, username: "cohesive" },
    { mmr: 2511, username: "disintermediate" },
    { mmr: 3342, username: "Decentralized" },
    { mmr: 2865, username: "Phased" },
    { mmr: 2193, username: "Progressive" },
    { mmr: 2545, username: "De-engineered" },
    { mmr: 2190, username: "6th generation" },
    { mmr: 2882, username: "tertiary" },
    { mmr: 2866, username: "Multi-tiered" },
    { mmr: 3968, username: "leverage" },
    { mmr: 3275, username: "local" },
    { mmr: 2927, username: "approach" },
    { mmr: 2148, username: "Up-sized" },
    { mmr: 2830, username: "Centralized" },
    { mmr: 2182, username: "object-oriented" },
    { mmr: 3626, username: "non-volatile" },
    { mmr: 2355, username: "global" },
    { mmr: 3740, username: "didactic" },
    { mmr: 2245, username: "Versatile" },
    { mmr: 2877, username: "Inverse" },
    { mmr: 2813, username: "initiative" },
    { mmr: 2703, username: "Mandatory" },
    { mmr: 3455, username: "4th generation" },
    { mmr: 2509, username: "solution-oriented" },
    { mmr: 2775, username: "didactic" },
    { mmr: 2158, username: "stable" },
    { mmr: 3409, username: "explicit" },
    { mmr: 2324, username: "didactic" },
    { mmr: 2359, username: "initiative" },
    { mmr: 2454, username: "ability" },
    { mmr: 2675, username: "Polarised" },
    { mmr: 2628, username: "disintermediate" },
    { mmr: 2008, username: "explicit" },
    { mmr: 3913, username: "interactive" },
    { mmr: 2618, username: "maximized" },
    { mmr: 3090, username: "5th generation" },
    { mmr: 3693, username: "Quality-focused" },
    { mmr: 3201, username: "reciprocal" },
    { mmr: 2166, username: "optimal" },
    { mmr: 2378, username: "firmware" },
    { mmr: 2832, username: "strategy" },
    { mmr: 3112, username: "Streamlined" },
    { mmr: 3019, username: "Persistent" },
    { mmr: 2709, username: "frame" },
    { mmr: 3923, username: "context-sensitive" },
    { mmr: 3325, username: "matrix" },
    { mmr: 3255, username: "Re-contextualized" },
    { mmr: 2481, username: "empowering" },
    { mmr: 2587, username: "Team-oriented" },
    { mmr: 3222, username: "Networked" }]